before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
env:
  global:
    - CONNECTION_STRING=postgresql://postgres:Password12!@localhost:5432/testdb
